CREATE DATABASE IF NOT EXISTS ddz DEFAULT CHARSET utf8mb4;
USE ddz;
CREATE TABLE IF NOT EXISTS account (
  id         INT PRIMARY KEY AUTO_INCREMENT,
  username   VARCHAR(40) NOT NULL UNIQUE,
  password   VARCHAR(64) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO account (username, password) VALUES
  (SHA1('p1'), SHA1('123456')),
  (SHA1('p2'), SHA1('123456')),
  (SHA1('p3'), SHA1('123456'))
ON DUPLICATE KEY UPDATE password = VALUES(password);
